		<article>

			<header class="project-header" id="">
				<img src="img/content/prototype/project-image.jpg" alt="Project Image">
				<div class="overlay-wrap">
					<div class="floating-text">
					<small>Launch Date</small>
					<h2><a class="local-link" href="#project-2">Project Name <span class="expand-icon"> info </span> </a></h2>
				</div>
					<a class="project-url" href="#"target=_blank>projecturl.com &rarr;</a>			
				</div>
			</header>
			
			<section class="project-content">

				<p class="intro">
					The Emotional Arcade engages technology to allow people to play competitive games using their own emotions.  The Arcade is an attempt to provide at least one space on the planet where unrestrained emotional outbursts are honored, and celebrated.
				</p>
				<p>
					What are we if not our emotions? In a world that increasingly limits sponteneous emotional expression, the installation creates a space for personal revelation. It’s  a chance to explore the patterns of feeling in a fun way. And everyone who plays gets a lollypop.
				</p>
			
			</section>
		
		</article>