

	<footer class="clearfix" id="footer">
		<small>All content &copy; Tribeca Film Institute 2012&ndash;2014</small></br>
		<small>Site by <a href="http://digitalfrontiersman.com">The Digital Frontiersman</a></small>
		<a class="fixed" id="top" href="#main"> <span class="icon-up"></span> </a>
	</footer>

 	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>

	<script src="js/plugins.js"></script>
	<script type="text/javascript" src="js/jquery.scrollTo.min.js"></script>
	<script type="text/javascript" src="js/jquery.localScroll.min.js"></script>
	<script type="text/javascript" src="js/waypoints.min.js"></script>
	<script src="js/main.js"></script>

	<script>
	    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
	    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
	    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
	    s.parentNode.insertBefore(g,s)}(document,'script'));
	</script>

</body>
</html>