

	<footer class="clearfix" id="footer">
		
		<!--Google Asynchrous Load SDK -->
				<script type="text/javascript">
				      window.___gcfg = {
				        lang: 'en-US'
				      };

				      (function() {
				        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				        po.src = 'https://apis.google.com/js/plusone.js';
				        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
				      })();
				</script>
			
		<div id="ford-logo"> <img src="img/ui/justfilms_logo.gif" alt="Just Films Ford Foundation"> </div>
		<div id="footer-info">
			<p><a href="mailto:interactive@tribecafilminstitute.org"target=_blank> Contact Us </a> |
			   <a href="https://tribecafilminstitute.org/pages/newsletter_sign_up"target=_blank> Newsletter</a> |
			   Site by <a href="http://digitalfrontiersman.com"target=_blank>Alex Bloom</a>
			</p>
		</div>
		<div id="copyright">All content &copy; Tribeca Film Institute 2012&ndash;2014</div>
		<a class="fixed" id="top" href="#main"> <span class="icon-up"></span> </a>
	</footer>

 	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>

	<script src="js/plugins.js"></script>
	<script src="//maps.googleapis.com/maps/api/js?key=AIzaSyBB5Scju_ZbRBgb3HCpXqDpfnHuJCHVX_s&sensor=true"></script>
	<script src="js/gmaps.js"></script>
	
	<script type="text/javascript" src="js/jquery.scrollTo.min.js"></script>
	<script type="text/javascript" src="js/jquery.localScroll.min.js"></script>
	<script type="text/javascript" src="js/waypoints.min.js"></script>
	<script src="js/main.js"></script>
	
	

	<script>
	    var _gaq=[['_setAccount','UA-1312040-9'],['_trackPageview']];
	    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
	    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
	    s.parentNode.insertBefore(g,s)}(document,'script'));
	</script>

</body>
</html>