 


<meta property="og:site_name" content="TFI Sandbox"/>
<meta property="fb:admins" content="8228569"/>
<!-- <meta name="fb:app_id" content="167329723445244"/> -->
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="website" />
<meta property="article:author" content="https://www.facebook.com/TribecaFilmInstitute"/>
<meta name="google-site-verification" content="">
 
 <link rel="shortcut icon" href="favicon.ico" />
 <link rel="apple-touch-icon" href="apple-touch-icon-precomposed.png"/>
 
 <link rel="stylesheet" href="css/normalize.min.css">
 <link rel="stylesheet" href="css/custom.css">
 <script type="text/javascript" src="//use.typekit.net/kxg3xpi.js"></script>
 <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

<!--<script src="js/vendor/modernizr-2.6.2.min.js"></script> -->	
 
 <!--[if lte IE 8]>
	<link rel="stylesheet" href="css/ie8.css">
	<![endif]-->
       
    </head>
<body> 
	
<!--Facebook Asynchrous Load SDK -->
	<script>
	      window.fbAsyncInit = function() {
	        FB.init({
	          appId      : '167329723445244',
	          xfbml      : true,
	          version    : 'v2.0'
	        });
	      };
	      (function(d, s, id){
	         var js, fjs = d.getElementsByTagName(s)[0];
	         if (d.getElementById(id)) {return;}
	         js = d.createElement(s); js.id = id;
	         js.src = "//connect.facebook.net/en_US/sdk.js";
	         fjs.parentNode.insertBefore(js, fjs);
	       }(document, 'script', 'facebook-jssdk'));		      
	    </script>

	
	<header class="clearfix" id="header">
	        <button type="button" id="toggle" role="button" aria-label="Toggle Navigation" class="lines-button x2">
	          <span class="lines"></span>
	        </button>
			<a class="" id="logo" href="index"><strong>TFI</strong> Sandbox</a>			
	</header>
	<nav id="primary-nav">
		
				<dl class="primary clearfix" id="discover-primary">
					<dt class="clearfix">
						<a href="discover">Discover</a> <br> 
						<small>Discover inspiring interactive projects.</small>
					</dt>
					<dd class="primary-link" id=""> 
						<a href="tfi-new-media-fund"> TFI New Media Fund <span class="icon-right"></span> </a>	
						<ul class="secondary clearfix" id="">	
							<li class="secondary-link" id=""> <a href="tfi-new-media-fund-2014"> 2014 </a> </li>
							<li class="secondary-link" id=""> <a href="tfi-new-media-fund-2013"> 2013 </a> </li>
							<li class="secondary-link" id=""> <a href="tfi-new-media-fund-2012"> 2012 </a> </li>
							<li class="secondary-link" id=""> <a href="tfi-new-media-fund-2011"> 2011 </a> </li>
						</ul>
					</dd>
					<dd class="primary-link" id=""> 	
						<a href="interactive-landscape"> Interactive Landscape <span class="icon-right"></span> </a>
					</dd>
				</dl>

				<dl class="primary clearfix" id="participate-primary">
					<dt class="clearfix">
						<a href="participate">Participate</a> <br> 
						<small>Participate in TFI’s broad slate of programming that aims to expand the knowledge around interactive storytelling.</small>
					</dt>
					<dd class="primary-link" id=""> 
						<a href="tfi-interactive"> TFI Interactive <span class="icon-right"></span> </a>
						<ul class="secondary clearfix" id="">
							<li class="secondary-link"> <a href="tfi-interactive-2014"> 2014 </a> </li>
							<li class="secondary-link"> <a href="tfi-interactive-2013"> 2013 </a> </li>
							<li class="secondary-link"> <a href="tfi-interactive-2012"> 2012 </a> </li>
						</ul>
					</dd>
					<dd class="primary-link" id=""> 
						<a href="tribeca-hacks"> Tribeca Hacks <span class="icon-right"></span> </a>
					</dd>
					<dd class="primary-link"> 
						<a href="education"> Education <span class="icon-right"></span> </a> 
					</dd>
				</dl>

				<dl class="primary clearfix" id="build-primary">
					<dt class="clearfix">
						<a href="build">Build</a> <br> 
						<small>Tools, resources and advice to build your own interactive project.</small>
					</dt>
					<dd class="primary-link" id="">
						<a href="project-management"> Project Management Guide <span class="icon-right"></span></a> 
						<ul class="secondary clearfix" id="secondary-pm-nav">
							
							<li class="secondary-link"> <a href="project-management-scoping"> 01. Scoping </a> </li>
							<li class="secondary-link"> <a href="project-management-timeline"> 02. Timeline </a> </li>
							<li class="secondary-link"> <a href="project-management-budget"> 03. Budget </a> </li>
							<li class="secondary-link"> <a href="project-management-team"> 04. Team </a> </li>
							<li class="secondary-link"> <a href="project-management-distribution"> 05. Distribution </a> </li>
							<li class="secondary-link"> <a href="project-management-prmarketing"> 06. PR / Marketing </a> </li>
							<li class="secondary-link"> <a href="project-management-sustainability"> 07. Sustainability </a> </li>
						</ul>
					</dd>
					<dd class="primary-link" id="TechResources"> 
						<a href="tech-resources"> Tech Resources <span class="icon-right"></span> </a>
					</dd>
					<dd class="primary-link"> 
						<a href="funding"> Funding <span class="icon-right"></span> </a> 
					</dd>
					<dd class="primary-link"> 
						<a href="festivals"> Festivals <span class="icon-right"></span> </a> 
					</dd>
					<dd class="primary-link"> 
						<a href="impact"> Impact <span class="icon-right"></span> </a> 
					</dd>
				</dl>
	
	</nav>

