 <link rel="stylesheet" href="css/normalize.min.css">
 <link rel="stylesheet" href="css/custom.css">
 <script type="text/javascript" src="//use.typekit.net/kxg3xpi.js"></script>
 <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

<!--<script src="js/vendor/modernizr-2.6.2.min.js"></script> -->	
 
 <!--[if lte IE 8]>
	<link rel="stylesheet" href="css/ie8.css">
	<![endif]-->
       
    </head>
<body> 
	<header class="clearfix" id="header">

			<a class="" id="logo" href="index"><strong>TFI</strong> Sandbox</a>
	        <button type="button" id="toggle" role="button" aria-label="Toggle Navigation" class="lines-button x2">
	          <span class="lines"></span>
	        </button>
			
	</header>
	<nav id="primary-nav" class="closed">
		
				<dl class="primary clearfix" id="discover-primary">
					<dt class="clearfix">Discover</dt>
					<dd class="primary-link" id=""> 
						<a href="tfi-new-media-fund"> TFI New Media Fund <span class="icon-right"></span> </a>	
						<ul class="secondary" id="">	
							<li class="secondary-link" id=""> <a href="#2013"> 2013 </a> </li>
							<li class="secondary-link" id=""> <a href="#2012"> 2012 </a> </li>
							<li class="secondary-link" id=""> <a href="#2011"> 2011 </a> </li>
						</ul>
					</dd>
					<dd class="primary-link" id=""> 	
						<a href="interactive-landscape"> Interactive Landscape <span class="icon-right"></span> </a>
						<ul class="secondary" id="">		
							<li class="secondary-link" id=""> <a href="#Web"> Web </a> </li>
							<li class="secondary-link" id=""> <a href="#Apps"> Apps </a> </li>
							<li class="secondary-link" id=""> <a href="#Installations"> Installatons </a> </li>
							<li class="secondary-link" id=""> <a href="#Other"> Other </a> </li>
						</ul>
					</dd>
				</dl>

				<dl class="primary clearfix" id="participate-primary">
					<dt class="clearfix">Participate</dt>
					<dd class="primary-link" id=""> 
						<a href="tfi-interactive"> TFI Interactive <span class="icon-right"></span> </a>
						<ul class="secondary" id="">
							<li class="secondary-link"> <a href="#2014"> 2014 </a> </li>
							<li class="secondary-link"> <a href="#2013"> 2013 </a> </li>
							<li class="secondary-link"> <a href="#2012"> 2012 </a> </li>
						</ul>
					</dd>
					<dd class="primary-link" id=""> 
						<a href="tribeca-hacks"> Tribeca Hacks <span class="icon-right"></span> </a>
						<ul class="secondary" id="">	
							<li class="secondary-link"> <a href="#upcoming"> Upcoming </a> </li>
							<li class="secondary-link"> <a href="#completed"> Completed </a> </li>
						</ul>
					</dd>
					<dd class="primary-link"> 
						<a href="education"> Education <span class="icon-right"></span> </a> 
					</dd>
					<dd class="primary-link"> 
						<a href="mit-fledgling-fund"> MIT Fledgling Fund <span class="icon-right"></span> </a> 
					</dd>
				</dl>

				<dl class="primary clearfix" id="build-primary">
					<dt class="clearfix">Build</dt>
					<dd class="primary-link" id="">
						<a href="project-management"> Project Management Guide <span class="icon-right"></span></a> 
						<ul class="secondary" id="">
							
							<li class="secondary-link"> <a href="#"> Building A Team </a> </li>
							<li class="secondary-link"> <a href="#"> Timelines </a> </li>
							<li class="secondary-link"> <a href="#"> Budgets </a> </li>
							<li class="secondary-link"> <a href="#"> Distribution </a> </li>
							<li class="secondary-link"> <a href="#"> Sustainability </a> </li>
							<li class="secondary-link"> <a href="#"> PR / Marketing </a> </li>
						</ul>
					</dd>
					<dd class="primary-link" id="TechResources"> 
						<a href="tech-resources"> Tech Resources <span class="icon-right"></span> </a>
						<ul class="secondary" id="">
							<li class="secondary-link"> <a href="#"> Code 101 </a> </li>
							<li class="secondary-link"> <a href="#"> Platforms </a> </li>
							<li class="secondary-link"> <a href="#"> Design </a> </li>
						</ul>
					</dd>
					<dd class="primary-link"> 
						<a href="funding"> Funding <span class="icon-right"></span> </a> 
					</dd>
					<dd class="primary-link"> 
						<a href="festivals"> Festivals <span class="icon-right"></span> </a> 
					</dd>
				</dl>
	
	</nav>

