<!DOCTYPE html>
<!--[if lt IE 9]> <p> You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/"> upgrade your browser</a> or <a href="http://whatbrowser.org/">try another browser</a> to improve your experience. </p>        <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]> <html class="no-js"> <![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">   
		<meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="viewport" content="width = device-width, initial-scale=1, maximum-scale=1, user-scalable = no">
		<meta name="keywords" content="Tribeca Film Institute, New Media, Trans Media, Film, Filmmaking, New York City, Resources, Grants, Festivals">
		
	   
		


		
		
		
		
		
		

		
		
		
		
		